import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '基础教程',
      link: {type: 'generated-index', title: '基础教程'},
      items: [{type: 'autogenerated', dirName: 'base_tutorials'}],
    },
    {
      type: 'category',
      label: '规范定义',
      link: {type: 'generated-index', title: '规范定义'},
      items: [{type: 'autogenerated', dirName: 'define'}],
    },
    {
      type: 'category',
      label: '外部资源',
      link: {type: 'generated-index', title: '外部资源'},
      items: [{type: 'autogenerated', dirName: 'external'}],
    },
  ],
  termsSidebar: [{type: 'autogenerated', dirName: 'terms'}],
};

export default sidebars;
